export const MAX_CONVERSATIONS_PER_USER = 10;
export const MAX_PERSISTED_MESSAGES_PER_CONVERSATION = 60;
export const MAX_MODEL_CONTEXT_MESSAGES = 30;
export const MAX_ESTIMATED_PROMPT_TOKENS = 12000;
export const ESTIMATED_CHARS_PER_TOKEN = 4;
