export const MAX_CONVERSATIONS_PER_USER = 20;
export const MAX_PERSISTED_MESSAGES_PER_CONVERSATION = 120;
export const MAX_MODEL_CONTEXT_MESSAGES = 40;
export const MAX_ESTIMATED_PROMPT_TOKENS = 12000;
export const ESTIMATED_CHARS_PER_TOKEN = 4;
